export type Categoria = "landings" | "mobile" | "dashboards" | "wellness" | "otros" | "default" | "refero";

export type Estilo = {
  slug: string;
  nombre: string;
  tagline: string;
  categoria: Categoria;
  descripcion: string;
  cuandoUsar: string;
  paleta: string[];
  tipografia: string;
  bgPreview: string;
  fgPreview: string;
  accentPreview: string;
  estado: "aprobado" | "aprobado" | "descartado";
};

export const ESTILOS: Estilo[] = [
  // === LANDINGS ===
  {
    slug: "dimes",
    nombre: "Dimes Studio",
    tagline: "Brutalist juvenil crudo",
    categoria: "landings",
    descripcion: "Bordes negros gruesos, sombras duras (no blur), color flat saturado, tipografÃ­a bold gigante. Memorabilidad alta, polariza.",
    cuandoUsar: "Marcas alternativas, productos creativos, estudios de diseÃ±o, branding que necesita personalidad fuerte.",
    paleta: ["#fffbed", "#ff6b35", "#004e89", "#0a0a0a", "#dfff00"],
    tipografia: "Bebas Neue + Inter",
    bgPreview: "#fffbed",
    fgPreview: "#0a0a0a",
    accentPreview: "#ff6b35",
    estado: "aprobado",
  },
  {
    slug: "modern-saas",
    nombre: "Modern Minimal SaaS",
    tagline: "Stripe / Linear / Vercel",
    categoria: "landings",
    descripcion: "Mucho aire, fonts grandes, gradients sutiles, animaciones de scroll. Para empresas tech, agencias creativas, productos digitales.",
    cuandoUsar: "Empresas tech, startups, SaaS, agencias creativas. Cuando se posiciona como moderno/innovador.",
    paleta: ["#ffffff", "#fafafa", "#5e6ad2", "#111827", "#6b7280"],
    tipografia: "Geist + Inter",
    bgPreview: "#ffffff",
    fgPreview: "#111827",
    accentPreview: "#5e6ad2",
    estado: "aprobado",
  },
  {
    slug: "ethereal",
    nombre: "Ethereal Artistic",
    tagline: "Obys / Hugo GarcÃ­a / Aristide",
    categoria: "landings",
    descripcion: "Layouts asimÃ©tricos, animaciones experimentales, mucha atmÃ³sfera. Negro/blanco roto, fonts display caros. Polariza pero genera memorabilidad alta.",
    cuandoUsar: "Sitios de autor, fotÃ³grafos, diseÃ±adores, marcas de nicho creativas.",
    paleta: ["#0a0a0a", "#fafaf7", "#ff3b00", "#222222", "#888888"],
    tipografia: "SÃ¶hne + Mono experimental",
    bgPreview: "#0a0a0a",
    fgPreview: "#fafaf7",
    accentPreview: "#ff3b00",
    estado: "aprobado",
  },
  {
    slug: "comercio-popular",
    nombre: "Comercio Popular AR",
    tagline: "Tiendanube / MercadoLibre vibe",
    categoria: "landings",
    descripcion: "Sitio funcional, claro, ordenado y rÃ¡pido. No 'design forward', sÃ­ pensado para que el cliente comÃºn entre y compre.",
    cuandoUsar: "Comercios locales: almacÃ©n, panaderÃ­a, ferreterÃ­a, kiosco, tienda online chica.",
    paleta: ["#ffffff", "#f8f9fa", "#16a34a", "#171717", "#737373"],
    tipografia: "Inter / system-ui",
    bgPreview: "#ffffff",
    fgPreview: "#171717",
    accentPreview: "#16a34a",
    estado: "aprobado",
  },

  // === MOBILE ===
  {
    slug: "ios-native",
    nombre: "iOS Native",
    tagline: "Sistema iOS / Threads",
    categoria: "mobile",
    descripcion: "Tab bar abajo, gestos, animaciones tipo spring. Para apps que la gente abre varias veces al dÃ­a.",
    cuandoUsar: "Apps diarias: turnos, hÃ¡bitos, tracking. Cuando la frecuencia de uso justifica feel nativo.",
    paleta: ["#ffffff", "#f2f2f7", "#007aff", "#000000", "#8e8e93"],
    tipografia: "SF Pro / system-ui",
    bgPreview: "#ffffff",
    fgPreview: "#000000",
    accentPreview: "#007aff",
    estado: "aprobado",
  },
  {
    slug: "material-3",
    nombre: "Material Design 3",
    tagline: "Android / Google",
    categoria: "mobile",
    descripcion: "Floating Action Button, elevation con sombras, ripples al touch. Material You theming.",
    cuandoUsar: "Apps con pÃºblico mayormente Android (Argentina mainstream).",
    paleta: ["#fef7ff", "#e8def8", "#6750a4", "#1d1b20", "#79747e"],
    tipografia: "Roboto / Roboto Flex",
    bgPreview: "#fef7ff",
    fgPreview: "#1d1b20",
    accentPreview: "#6750a4",
    estado: "aprobado",
  },
  {
    slug: "web-first-mobile",
    nombre: "Web-first Mobile",
    tagline: "Twitter / Airbnb mobile",
    categoria: "mobile",
    descripcion: "No parece app, es claramente web pero responde bien en mobile. Default cuando el usuario tambiÃ©n puede entrar desde desktop.",
    cuandoUsar: "Casi todo. Default mobile cuando el desktop tambiÃ©n importa.",
    paleta: ["#ffffff", "#f7f9fa", "#1d9bf0", "#0f1419", "#536471"],
    tipografia: "Inter / system-ui",
    bgPreview: "#ffffff",
    fgPreview: "#0f1419",
    accentPreview: "#1d9bf0",
    estado: "aprobado",
  },

  // === DASHBOARDS ===
  {
    slug: "linear",
    nombre: "Linear (real)",
    tagline: "Midnight command center Â· refero",
    categoria: "dashboards",
    descripcion: "Dark layered + neon lime accent Ãºnico. Valores REALES extraÃ­dos de refero.design (no adivinados). Para apps de uso diario, dashboards internos, herramientas para power users.",
    cuandoUsar: "Exo dashboard, organizadores internos, gestiÃ³n de tareas, panels tÃ©cnicos.",
    paleta: ["#08090a", "#0f1011", "#e4f222", "#f7f8f8", "#8a8f98"],
    tipografia: "Inter Variable + Berkeley Mono",
    bgPreview: "#08090a",
    fgPreview: "#f7f8f8",
    accentPreview: "#e4f222",
    estado: "aprobado",
  },
  {
    slug: "stripe-dashboard",
    nombre: "Stripe Dashboard",
    tagline: "SaaS premium amigable",
    categoria: "dashboards",
    descripcion: "MÃ¡s amigable que Linear, menos denso, pensado tambiÃ©n para no tÃ©cnicos. TipografÃ­a clara, grÃ¡ficos prolijos.",
    cuandoUsar: "Dashboards que tambiÃ©n ven clientes/usuarios externos. MÃ©tricas para Guadalupe, panel de Fatima.",
    paleta: ["#ffffff", "#f7f7f7", "#635bff", "#0a0a0a", "#6b7280"],
    tipografia: "Inter / SÃ¶hne",
    bgPreview: "#ffffff",
    fgPreview: "#0a0a0a",
    accentPreview: "#635bff",
    estado: "aprobado",
  },
  {
    slug: "airbnb-friendly",
    nombre: "Airbnb Friendly",
    tagline: "Notion / Intercom",
    categoria: "dashboards",
    descripcion: "Menos 'tech', mÃ¡s humano. Iconos simpÃ¡ticos, tono amigable, todo explicado con texto. Para usuarios completamente no tÃ©cnicos.",
    cuandoUsar: "Apps para no tÃ©cnicos. Comerciante de barrio que nunca usÃ³ software pro.",
    paleta: ["#ffffff", "#fafafa", "#ff5a5f", "#222222", "#717171"],
    tipografia: "Inter Variable / SÃ¶hne",
    bgPreview: "#ffffff",
    fgPreview: "#222222",
    accentPreview: "#ff5a5f",
    estado: "aprobado",
  },

  // === WELLNESS / KINE ===
  {
    slug: "calm",
    nombre: "Calm",
    tagline: "Wellness premium minimal",
    categoria: "wellness",
    descripcion: "Tonos tierra suaves, mucho aire, ritmo lento, serif elegante. Comunica calma, cuidado, espacio.",
    cuandoUsar: "Apps de wellness, tracking de salud, programas online de ejercicios, experiencias relajadas.",
    paleta: ["#f7f3ee", "#fff9f0", "#7d8471", "#c97c5d", "#2c2925"],
    tipografia: "Cormorant Garamond + Inter",
    bgPreview: "#f7f3ee",
    fgPreview: "#2c2925",
    accentPreview: "#7d8471",
    estado: "aprobado",
  },
  {
    slug: "sport-dinamico",
    nombre: "Sport DinÃ¡mico",
    tagline: "Nike Training / Strava",
    categoria: "wellness",
    descripcion: "EnergÃ­a visual, contraste alto, fotos en movimiento, tipografÃ­a bold. Comunica 'vamos para adelante, vos podÃ©s'.",
    cuandoUsar: "Apps fitness, programas de alto compromiso, marcas deportivas. Pacientes jÃ³venes activos.",
    paleta: ["#0a0a0a", "#1a1a1a", "#ff5722", "#fafafa", "#a3a3a3"],
    tipografia: "Anton / Bebas + Inter",
    bgPreview: "#0a0a0a",
    fgPreview: "#fafafa",
    accentPreview: "#ff5722",
    estado: "aprobado",
  },
  {
    slug: "medico-amigable",
    nombre: "MÃ©dico Amigable",
    tagline: "Hinge Health / Brightline",
    categoria: "wellness",
    descripcion: "Confiable como software mÃ©dico pero accesible. Stripe + Calm. Para pacientes que buscan calidad seria sin sentirse en hospital.",
    cuandoUsar: "Apps de salud para pacientes. Punto medio entre wellness premium y software clÃ­nico.",
    paleta: ["#ffffff", "#f1f5f9", "#3b82f6", "#0f172a", "#f59e0b"],
    tipografia: "Inter Display + Inter",
    bgPreview: "#ffffff",
    fgPreview: "#0f172a",
    accentPreview: "#3b82f6",
    estado: "aprobado",
  },
  {
    slug: "clinico-calmado",
    nombre: "ClÃ­nico Calmado",
    tagline: "SimplePractice / Practice Better",
    categoria: "wellness",
    descripcion: "Software mÃ©dico moderno. Todo aireado, blanco/celeste, foco en claridad. Confianza profesional.",
    cuandoUsar: "Organizador interno del kine (vista del profesional, no del paciente). Software clÃ­nico.",
    paleta: ["#ffffff", "#f8fafc", "#0ea5e9", "#0f172a", "#64748b"],
    tipografia: "Inter / Nunito",
    bgPreview: "#ffffff",
    fgPreview: "#0f172a",
    accentPreview: "#0ea5e9",
    estado: "aprobado",
  },

  // === OTROS ===
  {
    slug: "operativo-calido",
    nombre: "Operativo CÃ¡lido",
    tagline: "Tiendanube admin / MP",
    categoria: "otros",
    descripcion: "Dashboard simple sin pretensiÃ³n 'tech moderno'. Pensado para que entren, vean de un golpe quÃ© pasa, no se compliquen.",
    cuandoUsar: "Dashboard interno para no tÃ©cnicos en negocios chicos. WhatsApp Fatima, panel para administrar pedidos.",
    paleta: ["#fafafa", "#ffffff", "#16a34a", "#f97316", "#171717"],
    tipografia: "Inter / system-ui",
    bgPreview: "#fafafa",
    fgPreview: "#171717",
    accentPreview: "#16a34a",
    estado: "aprobado",
  },

  // === REFERO (extraÃ­dos con DESIGN.md real) ===
  {
    slug: "stripe-real",
    nombre: "Stripe (real)",
    tagline: "Digital command center Â· refero",
    categoria: "refero",
    descripcion: "Paleta y tokens REALES extraÃ­dos de refero.design. Deep Violet #533afd, Midnight Ink, Sohne-var. Eficiencia tranquila con elevaciÃ³n sutil.",
    cuandoUsar: "Plataformas financieras, fintech, infra que requiere transmitir confiabilidad tÃ©cnica.",
    paleta: ["#ffffff", "#f6f9fc", "#533afd", "#061b31", "#425466"],
    tipografia: "Sohne-var + Source Code Pro",
    bgPreview: "#ffffff",
    fgPreview: "#061b31",
    accentPreview: "#533afd",
    estado: "aprobado",
  },
  {
    slug: "cursor",
    nombre: "Cursor",
    tagline: "Warm ivory software studio Â· refero",
    categoria: "refero",
    descripcion: "DESIGN.md real de cursor.com. Canvas Parchment cÃ¡lido + Inkwell, sombras multi-capa, densidad compacta. EstÃ©tica 'estudio de software cÃ¡lido'.",
    cuandoUsar: "Tools dev, IDEs, productos tÃ©cnicos que quieren comunicar precisiÃ³n sin frialdad.",
    paleta: ["#f7f7f4", "#262510", "#7a7974", "#f54e00", "#e6e5e0"],
    tipografia: "CursorGothic + Berkeley Mono + Lato",
    bgPreview: "#f7f7f4",
    fgPreview: "#262510",
    accentPreview: "#f54e00",
    estado: "aprobado",
  },
  {
    slug: "steep",
    nombre: "Steep",
    tagline: "Warm crisp canvas Â· refero",
    categoria: "refero",
    descripcion: "Analytics platform. White canvas con warm mist accent, serif Signifier para gravitas + Sohne para claridad. Sombras sutiles, restraint elegance.",
    cuandoUsar: "Dashboards de datos, BI tools, plataformas analytics que combinan rigor con calidez.",
    paleta: ["#ffffff", "#f7f7f8", "#fbe1d1", "#5d2a1a", "#17191c"],
    tipografia: "Sohne + Signifier",
    bgPreview: "#ffffff",
    fgPreview: "#17191c",
    accentPreview: "#5d2a1a",
    estado: "aprobado",
  },
  {
    slug: "monopo",
    nombre: "monopo.vn",
    tagline: "Frosted glass, shifting gradients Â· refero",
    categoria: "refero",
    descripcion: "Estudio de diseÃ±o vietnamita. Dark + organic shifting gradients sobre frosted glass. Roobert/Raleway, ghost buttons con border-radius 75.024px.",
    cuandoUsar: "Estudios de diseÃ±o, agencias, portfolios creativos con personalidad atmosfÃ©rica.",
    paleta: ["#000000", "#181818", "#ffffff", "#6d6d6d", "#636363"],
    tipografia: "Roobert + Raleway",
    bgPreview: "#000000",
    fgPreview: "#ffffff",
    accentPreview: "#6d6d6d",
    estado: "aprobado",
  },

  // === DEFAULT ===
  {
    slug: "sin-estilo",
    nombre: "Sin estilo",
    tagline: "Default placeholder â€” no decisions yet",
    categoria: "default",
    descripcion: "LÃ­nea fina B/N, Roboto Mono, border-radius 0, cero acentos. Comunica claramente que falta decisiÃ³n de diseÃ±o.",
    cuandoUsar: "Default cuando NO se eligiÃ³ estilo del mood board todavÃ­a. Evita que un mockup con shadcn-default se confunda con producto terminado.",
    paleta: ["#ffffff", "#000000", "#666666", "#000000", "#000000"],
    tipografia: "Roboto Mono",
    bgPreview: "#ffffff",
    fgPreview: "#000000",
    accentPreview: "#000000",
    estado: "aprobado",
  },
];

export const CATEGORIAS: { id: Categoria; label: string; descripcion: string }[] = [
  { id: "landings", label: "Landings comerciales", descripcion: "Sitios para mostrar productos/servicios + contacto" },
  { id: "mobile", label: "Apps mobile", descripcion: "Web apps usadas principalmente desde el celular" },
  { id: "dashboards", label: "Dashboards / apps internas", descripcion: "Herramientas internas: admin, mÃ©tricas, gestiÃ³n" },
  { id: "wellness", label: "Wellness / kine / salud", descripcion: "Apps de salud, programas online, software clÃ­nico" },
  { id: "otros", label: "Otros operativos", descripcion: "Dashboards especÃ­ficos para nichos" },
  { id: "refero", label: "ExtraÃ­dos con refero.design", descripcion: "DESIGN.md real de sitios reales â€” paleta y tipografÃ­a con valores exactos, no adivinados" },
  { id: "default", label: "Default sin estilo", descripcion: "Placeholder cuando todavÃ­a no hay decisiÃ³n" },
];

export function getEstilo(slug: string): Estilo | undefined {
  return ESTILOS.find((e) => e.slug === slug);
}
